"""add report_markdown to jobs

Revision ID: 0bb20f2510f4
Revises: 39cb2a65604d
Create Date: 2026-05-10 16:17:41.415340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb20f2510f4'
down_revision: Union[str, Sequence[str], None] = '39cb2a65604d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('report_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'report_markdown')
    # ### end Alembic commands ###
