"""add search_source to tech_queries

Revision ID: f61742926283
Revises: 0bb20f2510f4
Create Date: 2026-05-11 11:18:51.885553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61742926283'
down_revision: Union[str, Sequence[str], None] = '0bb20f2510f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_queries', sa.Column('search_source', sa.String(length=30), server_default='semantic_scholar', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_queries', 'search_source')
    # ### end Alembic commands ###
